### ISSUE TITLE
Stops counting after hot-swap

### ISSUE THREAD

**Issue by simonh1000** [basti1302/elm-reactor-custom-html#1]
Just downloaded and installed your code :-)

What I see when I edit the code is
- the words change - great!
- the counter stops
- the counter in the debug panel continues incrementing

I get the same (without styling) at http://localhost:8000/Main.elm?debug too

**Comment by basti1302** [comment]
Hm, yeah, that's true. I didn't notice but it behaves as you described. 

As a workaround, you can refresh the browser and the counts starts at 0 again. Of course, the point is that you don't have to refresh manually :-(

However, I wouldn't know what to do about it. Maybe that's worth a bug report at elm-lang/elm-reactor?
