### ISSUE TITLE
Upgrade to elm 0.16.0

### ISSUE THREAD

**Issue by ibirrer** [basti1302/elm-reactor-custom-html#3]
I tried to upgrade to elm 0.16.0. See https://github.com/ibirrer/elm-reactor-custom-html/commit/379ad1d1debca40f6bfa65a1d6c8a3cb4dd4e4fa

Unfortunately, hot-swap does not work anymore after the upgrade. Any idea what's wrong with it?

**Comment by basti1302** [comment]
I've also trouble with hot-swap since v0.16.0, even when using elm-reactor straight away with the Elm file. For me it is just broken atm.

**Comment by basti1302** [comment]
I'd like to have that as a pull request anyway, if you don't mind. I'll just put a big fat warning in the readme that elm-reactor does not work currently (which renders this repo a bit useless). 

The point is that elm-reactor hopefully will get fixed, maybe with a bugfix version for 0.16 and then this setup might just work again.

**Comment by ibirrer** [comment]
Sure, see https://github.com/basti1302/elm-reactor-custom-html/pull/4
